

---
# ***Argentina Programa 4.0 - Programación Avanzada con Python***
---

## **Módulo 4**: Librería NumPy - Práctica - Solución

### ***Universidad Nacional de Chilecito***

---


La idea de esta práctica es ejercitar los puntos que vamos a necesitar para resolver el desafío.

Usaremos un resumen del dataset de Kaggle que tiene datos de ventas:

https://www.kaggle.com/kyanyoga/sample-sales-data

## Ejercicio 1
Leer los datos del archivo [/Data/sales_data_sample_excercise.csv](https://drive.google.com/file/d/1iQmgUE0RjoUdptS3O_7ekGwF9bZp09d7/view?usp=drive_link)

Este archivo tiene algunos datos numéricos y otros de tipo cadena de caracteres.

Las columnas son:

* ORDERNUMBER: int, id de la orden

* SALES: float, monto abonado

* MONTH_ID: int, mes

* YEAR_ID: int, año

* PRODUCTLINE: str, producto

* COUNTRY: str, país de venta

¿Recuerdan que todos los elementos de una instancia de ndarray deben ser del mismo tipo? Entonces vamos a leer el archivo y crear una instancia de ndarray de tipo cadena de caracteres.


Con ayuda del siguiente código podrás vincular tu cuenta de Google Drive.


En la siguiente carpeta se encuentran los diferentes dataset que vayamos usando en el curso.

[Carpeta con datos a usar](https://drive.google.com/drive/folders/18UJ1OiBYVPhoYVVcGdFVMle6VQo2pfnc?usp=drive_link)



Deberás:

* Darle click derecho a la carpeta AP_UNdeC y seleccionar la opción de Añadir acceso directo a Drive

* Seleccionar que se añada en Mi Unidad, dentro de Todas las ubicaciones

* Listo
Con esto, ya tendrás acceso a los archivos que nosotros subamos siempre.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')
pathCurso = '/content/drive/MyDrive/AP_UNdeC/Data/'

Mounted at /content/drive


Con el siguiente comando podrás establecer la ruta del archivo que vamos a necesitar en ésta ocasión:

In [ ]:
import numpy as np

data_location = pathCurso + 'sales_data_sample_excercise.csv'

Con el siguiente código podrás importar el archivo:

In [ ]:
data_type_default = np.genfromtxt(data_location, skip_header=1, delimiter='\t')
data_type_default

array([[1.01070e+04, 2.87100e+03, 2.00000e+00, 2.00300e+03,         nan,
                nan],
       [1.01210e+04, 2.76590e+03, 5.00000e+00, 2.00300e+03,         nan,
                nan],
       [1.01340e+04, 3.88434e+03, 7.00000e+00, 2.00300e+03,         nan,
                nan],
       ...,
       [1.03860e+04, 5.41757e+03, 3.00000e+00, 2.00500e+03,         nan,
                nan],
       [1.03970e+04, 2.11616e+03, 3.00000e+00, 2.00500e+03,         nan,
                nan],
       [1.04140e+04, 3.07944e+03, 5.00000e+00, 2.00500e+03,         nan,
                nan]])

In [ ]:
data_type_str = np.genfromtxt(data_location, skip_header=1, delimiter='\t', dtype= str)
data_type_str

In [ ]:
data_type_int = np.genfromtxt(data_location, skip_header=1, delimiter='\t', dtype= int)
data_type_int

In [ ]:
data_type_float = np.genfromtxt(data_location, skip_header=1, delimiter='\t', dtype= float)
data_type_float

# Ejercicio 2 - Tipos

Crear un array numérico que tenga como valores las columna SALES y otro array de str que tenga como valores la columna COUNTRY

Ayuda: https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html

In [ ]:
data = np.genfromtxt(data_location, skip_header=1, delimiter='\t', dtype= str)

sales_vector_str = data[:, 1]
sales_vector =  sales_vector_str.astype(np.float)
print(sales_vector)

country_vector = data[:, 5]
print(country_vector)


[2871.   2765.9  3884.34 ... 5417.57 2116.16 3079.44]
['USA' 'France' 'France' ... 'Spain' 'France' 'USA']


<ipython-input-4-9980f196b480>:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  sales_vector =  sales_vector_str.astype(np.float)


## Ejercicio 3 - Funciones de agregación

Sobre los datos de precios de ventas (columna SALES) calcular:

* mínimo

* máximo

* promedio

* cantidad

* suma

Ayuda: https://docs.scipy.org/doc/numpy-1.17.0/reference/routines.statistics.html

In [ ]:
np.min(sales_vector)

In [ ]:
np.max(sales_vector)

In [ ]:
np.average(sales_vector)

In [ ]:
sales_vector.size

In [ ]:
np.sum(sales_vector)

## Ejercicio 4 - Indexing

a) ¿Cuántas ventas se hicieron en USA?

Ayuda: boolean indexing

b) ¿Cuáles son los precios de las 5 ventas que están en las filas 6 a 10 del dataset?

Resolvamos usando array slicing y fancy indexing

Ayuda: recuerden `range` https://docs.python.org/3/library/functions.html#func-range

In [ ]:
print(country_vector)
mask = country_vector == 'USA'
print(mask)
country_vector_USA = country_vector[mask]
country_vector_USA.size


['USA' 'France' 'France' ... 'Spain' 'France' 'USA']
[ True False False ... False False  True]


1004

In [ ]:
# array slicing:
sales_vector_slicing = sales_vector[6:11]
# observemos que el límite superior no está incluído
print(sales_vector_slicing)

[2497.77 5512.32 2168.54 4708.44 3965.66]


In [ ]:
# fancy indexing

indexes = range(6, 11, 1)
indexes_int = [6, 7, 8, 9, 10]
sales_vector_fancy = sales_vector[indexes_int]
print(sales_vector_fancy)


[2497.77 5512.32 2168.54 4708.44 3965.66]


In [ ]:
# veo que obtengo el mismo resultado con una u otra forma de indexación:

# una forma es comparar elemento a elemento los dos arrays:
print(sales_vector_slicing == sales_vector_fancy)

# otra forma es ver si la cantidad de elementos que son iguales en los dos arrays (sum(sales_vector_slicing == sales_vector_fancy))
# es igual a la cantidad total de elementos por array
cant_elem = len(sales_vector_slicing)
print(sum(sales_vector_slicing == sales_vector_fancy) == cant_elem)

# y otra forma es ver si ningún elemento distinto, o sea negar any:
print(not any(sales_vector_slicing != sales_vector_fancy))

[ True  True  True  True  True]
True
True
